# in your terminal, run conda: conda env create -f environment.yaml
name: paper-plca-grid-expansion
channels:
  - conda-forge
  - cmutel
dependencies:
  - ipython
  - ipykernel
  - bw2data==4.5
  - bw2calc
  - brightway25
  # - brightway25_nosolver # for macOS ARM machine
  # - scikit-umfpack # for macOS ARM machine
  # - numpy==1.24 # for macOS ARM machine
  - pip
  - pip:
    - rwthcolors
    - premise==2.3.0dev1